agents:
  - agent_ls
  - agent_dc
  - agent_bat
location: ny
cintensity_file: 'NYIS_NG_&_avgCI.csv'
weather_file: 'USA_NY_New.York-Kennedy.epw'
workload_file: 'Alibaba_CPU_Data_Hourly_1.csv'
max_bat_cap_Mw: 2
individual_reward_weight: 0.8
flexible_load: 0.4
ls_reward: default_ls_reward
dc_reward: default_dc_reward
bat_reward: default_bat_reward
dc_config_file: 'dc_config.json'
partial_obs: True
nonoverlapping_shared_obs_space: True