datacenters:
  - dc_id: 1
    location: "US-CAL-CISO"
    timezone_shift: -7
    population_weight: 0.18
    total_cores: 50000
    total_gpus: 1000
    total_mem: 80000
    dc_config_file: "configs/dcs/dc_config.json"

  - dc_id: 2
    location: "DE-LU"
    timezone_shift: 1
    population_weight: 0.22
    total_cores: 85000
    total_gpus: 600
    total_mem: 80000
    dc_config_file: "configs/dcs/dc_config.json"

  - dc_id: 3
    location: "BR-SP"
    timezone_shift: -3
    population_weight: 0.2
    total_cores: 110000
    total_gpus: 300
    total_mem: 60000
    dc_config_file: "configs/dcs/dc_config.json"

  - dc_id: 4
    location: "SG"
    timezone_shift: 8
    population_weight: 0.25
    total_cores: 15000
    total_gpus: 700
    total_mem: 50000
    dc_config_file: "configs/dcs/dc_config.json"
  
  - dc_id: 5
    location: "AU-NSW"
    timezone_shift: 11
    population_weight: 0.15
    total_cores: 25000
    total_gpus: 300
    total_mem: 60000
    dc_config_file: "configs/dcs/dc_config.json"