simulation:
  year: 2023
  month: 8
  init_day: 1
  init_hour: 5
  duration_days: 7
  timestep_minutes: 15

  workload_path: "data/workload/alibaba_2020_dataset/result_df_full_year_2020.pkl"
  cloud_provider: "aws"
  shuffle_datacenters: true
  strategy: "manual_rl"
  use_tensorboard: true
  log_dir: "runs/train_run"
